services:
  oracle-itp:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle-itp
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: Oracle@168
      ENABLE_ARCHIVELOG: true
    volumes:
      - ./init_scripts:/opt/oracle/scripts/startup
      - oracle_data_itp:/opt/oracle/oradata
      - oracle_fra_cdc:/opt/oracle/fast_recovery_area
    networks:
      - itp-net

volumes:
  oracle_data_itp:
  oracle_fra_cdc:

networks:
  itp-net:
    external: true


