server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: git,vault
  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: TOKEN
          token: myroot
          # vault key value and version
          kv-version: 2
          backend: secret
          profile-separator: /
        git:
          uri: ${GL_URI}
          username: ${GL_USER}
          password: ${GL_TOKEN}
          search-paths: "/**"
          default-label: main
